# Generated by Django 4.2.8 on 2024-01-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoryMgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField(default=0)),
                ('old_price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('is_new', models.BooleanField()),
                ('is_featured', models.BooleanField()),
                ('short_description', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to='uploads/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoryMgt.category')),
            ],
        ),
    ]
